POST http://localhost:5555/user/login HTTP/1.1
token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbmEwMjg1MTFAZ21haWwuY29tIiwiaWQiOiI2MjQ2NWNjOTYwNTI3YzEzNTU2ZDFkOWUiLCJyb2xlIjoidXNlciIsImlhdCI6MTY0ODgyNjYyMX0.3Gzq0T6HqbjwJZJ13FVAHQlvIstRuf_BzC4z3_3pNWs
Content-Type: application/json

{
  "email": "rana028511@gmail.com",
  "password": "1111"
}

###

GET http://localhost:5555/user HTTP/1.1
token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbmEwMjg1MTFAZ21haWwuY29tIiwiaWQiOiI2MjQ2NWNjOTYwNTI3YzEzNTU2ZDFkOWUiLCJyb2xlIjoidXNlciIsImlhdCI6MTY0ODgyNjYyMX0.3Gzq0T6HqbjwJZJ13FVAHQlvIstRuf_BzC4z3_3pNWs
